{
	"c": "Price Now",
	"t1": "I bought",
	"t2": "BTC of",
	"t3": "The unit value of",
	"t4": "was",
	"t5": "BTC",
	"t6": "So my balance of",
	"t7": "is:",
	"t8": "My profit estimate is ",
	"t9": "%",
	"t10": "So i have to sell my",
	"t11": "at:",
	"t12": "(BTC)",
	"t13": "and my profit on BTC will be: ",
	"t14": "Font: ",
	"place": "name of currency",
	"fee": "with fee percent",
	"btn1": "Save",
	"btn2": "Clear",
	"btn3": "Show/Hide Table",
	"table1": "Date",
	"table2": "Currency",
	"table3": "Bought (BTC)",
	"table4": "Unit Value (BTC)",
	"table5": "Fee",
	"table6": "Amount",
	"table7": "Price to Sell (BTC)",
	"table8": "Profit (BTC)"
}