{
	"c": "Cotação atual",
	"t1": "Comprei",
	"t2": "BTC em",
	"t3": "O valor unitário do",
	"t4": "era de",
	"t5": "BTC",
	"t6": "Então meu saldo em",
	"t7": "é de:",
	"t8": "Minha estimativa de lucro é de ",
	"t9": "%",
	"t10": "Então terei que vender meus",
	"t11": "em:",
	"t12": "(BTC)",
	"t13": "E meu lucro em BTC será de: ",
	"t14": "Fonte: ",
	"place": "Nome da moeda",
	"fee": "Com taxa de: ",
	"btn1": "Salvar",
	"btn2": "Limpar",
	"btn3": "Mostrar/Ocultar Tabela",
	"table1": "Data",
	"table2": "Moeda",
	"table3": "Comprado (BTC)",
	"table4": "Valor Unitário (BTC)",
	"table5": "Taxa",
	"table6": "Saldo",
	"table7": "Preço para Venda (BTC)",
	"table8": "Lucro (BTC)"
}